### ISSUE TITLE
blockraft.oline is blocked.

### ISSUE THREAD

**Issue by Adithr123** [blockcraftio/blockcraft-public#14]
can you allow us to host this ourselves on repl.it?

**Comment by qhyun2** [comment]
what network are you trying to access it from? I'm guessing school right? which school board?

**Comment by Adithr123** [comment]
school computer, home wifi.

**Comment by Adithr123** [comment]
but https://gold.blockcraft.online isnt...

**Comment by Adithr123** [comment]
nvm

**Comment by qhyun2** [comment]
is it unblocked now?

**Comment by Adithr123** [comment]
No.

**Comment by Adithr123** [comment]
If i may ask, can you add a .replit file with the language and a run command?

**Comment by qhyun2** [comment]
This project uses Webpack and needs to be built before it can be run. I don't think it could ever work on replit. You can use https://blockdev.victorwei.com which should be unblocked

**Comment by Adithr123** [comment]
ok thnks!

**Comment by Adithr123** [comment]
but it is completely unupdated

**Comment by Adithr123** [comment]
not even the server names
